name: deploy

on:
  push:
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      # Setup

      - uses: actions/checkout@v3

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - uses: actions/setup-node@v3
        with:
          cache: "npm"
          cache-dependency-path: "**/package-lock.json" # je peine à croire que j'ai besoin d'écrire ça en v3...

      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          workload_identity_provider: "projects/94669066373/locations/global/workloadIdentityPools/github/providers/github"
          service_account: "app-engine-deployer@admin-338415.iam.gserviceaccount.com"

      # Build/Deploy

      - name: build-ihm
        run: |
          cd ihm
          npm ci
          npm run build

      - name: build-server
        run: |
          cd web-server
          echo "BILLETWEB_API_KEY=${{ secrets.BILLETWEB_API_KEY }}" > .env

      - id: "deploy"
        name: "Deploy to App Engine"
        uses: "google-github-actions/deploy-appengine@v1"
        with:
          deliverables: "ihm/ihm.yaml web-server/web-server.yaml web-server/dispatch.yaml"
          version: ${{ steps.get_version.outputs.VERSION }}

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        if: always()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: Déploiement de la billetterie réussi
          SLACK_MESSAGE: https://billetterie.gdgnantes.com
          SLACK_ICON: https://github.com/fluidicon.png
          SLACK_USERNAME: Github Actions
